### ISSUE TITLE
Upgrade to Django 1.11

### ISSUE THREAD

**Issue by kamil-i2a** [andymckay/django-aesfield#13]
@andymckay Could you please update it so it works with Django 1.11? `setup.py` states this package does not support it.

**Comment by EnTeQuAk** [comment]
I'll update this shortly, the package does work with Django 1.11 though.

**Comment by kamil-i2a** [comment]
@EnTeQuAk Great, thanks!

**Comment by EnTeQuAk** [comment]
django-aesfield 2.0 got released pushing compatibility to 2.x and 1.11, removing support for 1.10 and 1.9 though. They should still work, they're not tested anymore though.
