### ISSUE TITLE
Upgrade to Django 2.0

### ISSUE THREAD

**Issue by alex071995** [andymckay/django-aesfield#14]
Greetings, when you make the migration to version 2.0

**Comment by andymckay** [comment]
I don't focus on this repository any more, pull requests to support Django 2.0 (if possible in a backwards compatible way) are appreciated.

**Comment by EnTeQuAk** [comment]
django-aesfield 2.0 got released pushing compatibility to 2.x, removing support for 1.10 and 1.9 though. They should still work, they're not tested anymore though.

**Comment by andymckay** [comment]
Thanks @EnTeQuAk.
